{% set name = "nettrustscore" %}
{% set version = "2.0.7" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yaniker/nettrustscore-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9631e776298c3a61fd1f9fad6c69b6444e17f9ca591fa80e895fbba923f5fd1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - scikit-learn >=1.0
    - matplotlib-base >=3.0

test:
  imports:
    - trustquant
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/yaniker/nettrustscore-python
  summary: '[DEPRECATED] Please use trustpy-tools instead.'
  description: |
    !!! THIS PACKAGE IS DEPRECATED !!! Please use the actively maintained trustpy-tools
    instead. --> https://anaconda.org/conda-forge/trustpy-tools.
    NetTrustScore is a Python library that provides trustworthiness quantification
    metrics (how much you can trust the results generated by the system) for
    predictive models based on SoftMax-like outputs. Designed for easy integration
    into deep learning models (DL package independent) and classifications systems.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yaniker
