{% set name = "nettrustscore" %}
{% set version = "2.0.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yaniker/nettrustscore-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9a79e60cb03966155d26efadd4636f6fe670402ebd93bb45cf4bfc9ce64b50a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - scikit-learn >=1.0
    - matplotlib-base >=3.0

test:
  imports:
    - trustquant
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/yaniker/nettrustscore-python
  summary: 'Trustworthiness analysis for predictive models'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yaniker
